apiVersion: v1
kind: Namespace
metadata:
  name: postgres

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: data_engineer
  POSTGRES_USER: data_engineer
  POSTGRES_PASSWORD: password
