apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vol
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Changed from storage-class-name to standard
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-postgres
          image: busybox
          command: ["sh", "-c", "rm -rf /var/lib/postgresql/data/*"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-vol
      containers:
        - name: postgres
          image: postgres:latest  # Added latest tag for version specificity
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: data_engineer
            - name: POSTGRES_USER
              value: data_engineer
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-vol
          resources:  # Added resource requests and limits
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: postgres-vol
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
